output: false

pre-commit:
  commands:
    format:
      glob: "*.{ts,json}"
      run: npx biome check --write {staged_files}
      stage_fixed: true
    typecheck:
      glob: "*.ts"
      run: npx tsc --noEmit
